import turtle

back= turtle.Screen()
back.bgcolor('darkred')

tim=turtle.Turtle()
tim.color("pink")
tim.pensize(14)
tim.shape("turtle")
tim.speed(5)
tim.left(30)
tim.stamp()
tim.forward(100)
tim.stamp()
tim.left(270)
tim.stamp()
tim.forward(100)
tim.stamp()
tim.right(90)
tim.stamp()
tim.forward(200)
tim.stamp()
tim.right(90)
tim.stamp()
tim.forward(200)
tim.stamp()
tim.right(90)
tim.stamp()
tim.forward(100)
tim.stamp()
tim.right(90)
tim.stamp()
tim.forward(100)
tim.stamp()

back.mainloop()
